# Generated by Django 5.0.14 on 2026-08-11 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_capture_mode'),
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_url', models.TextField()),
                ('max_pages', models.IntegerField(default=100)),
                ('requests_per_second', models.FloatField(default=1.0)),
                ('concurrency', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=10)),
                ('pages_visited', models.IntegerField(default=0)),
                ('stop_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_jobs', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
