# Generated by Django 5.0.14 on 2026-08-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_crawljob'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='review_status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('tested', 'Tested'), ('interesting', 'Interesting')], default='unreviewed', max_length=15),
        ),
    ]
