# Generated by Django 5.0.14 on 2026-08-11 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeaterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('url', models.TextField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('body', models.TextField(blank=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeater_entries', to='core.project')),
                ('source_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic.flow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
