# Generated by Django 5.0.14 on 2026-08-11 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntruderAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('url', models.TextField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('body', models.TextField(blank=True)),
                ('attack_type', models.CharField(choices=[('sniper', 'Sniper')], default='sniper', max_length=20)),
                ('payload_set', models.TextField(blank=True, help_text='One payload per line.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intruder_attacks', to='core.project')),
                ('source_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic.flow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntruderResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('response_snippet', models.TextField(blank=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='intruder.intruderattack')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
