# Generated by Django 5.0.14 on 2026-08-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intruder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intruderresult',
            name='response_snippet',
        ),
        migrations.AddField(
            model_name='intruderresult',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intruderresult',
            name='request_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intruderresult',
            name='request_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='intruderresult',
            name='request_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intruderresult',
            name='response_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intruderresult',
            name='response_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
