# Generated by Django 5.0.14 on 2026-08-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='capture_mode',
            field=models.CharField(choices=[('all', 'Save all proxied traffic'), ('in_scope', 'Save in-scope traffic only')], default='all', max_length=10),
        ),
    ]
