# Generated by Django 5.0.14 on 2026-08-11 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_capture_mode'),
        ('scanner', '0001_initial'),
        ('traffic', '0002_crawljob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='core.project')),
                ('source_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic.flow')),
            ],
            options={
                'ordering': ['host', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='technology',
            constraint=models.UniqueConstraint(fields=('project', 'host', 'name'), name='unique_technology'),
        ),
    ]
