# Generated by Django 5.0.14 on 2026-08-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_capture_mode'),
        ('scanner', '0002_technology_technology_unique_technology'),
        ('traffic', '0003_flow_note_flow_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='finding',
            name='is_structural',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_structural', True)), fields=('project', 'source', 'title', 'host'), name='unique_structural_finding'),
        ),
    ]
