# Generated by Django 5.0.14 on 2026-08-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_vulnerability'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='review_status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('confirmed', 'Confirmed'), ('false_positive', 'False Positive')], default='unreviewed', max_length=15),
        ),
    ]
