# Generated by Django 5.0.14 on 2026-08-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='tool',
            field=models.CharField(choices=[('nmap', 'nmap'), ('searchsploit', 'searchsploit'), ('nuclei', 'nuclei'), ('nuclei_update', 'nuclei template update')], max_length=20),
        ),
    ]
